name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a # v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
