name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          set -euo pipefail
          cd pkg && go test -v -json -count=1 -cover -timeout 5m -parallel 4 ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
